default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: demo_ridgepole_development

test:
  <<: *default
  database: demo_ridgepole_test

production:
  <<: *default
  database: demo_ridgepole_production
  username: demo_ridgepole
  password: <%= ENV['DEMO_RIDGEPOLE_DATABASE_PASSWORD'] %>
